name: qtp
channels:
  - conda-forge
dependencies:
  - notebook=6.4.0
  - ipykernel=5.5.5
  - ipywidgets=7.6.3
  - nb_conda_kernels=2.3.1
  - numpy=1.21.0
  - pandas=1.2.5
  - pip
  - plotnine=0.8.0
  - pytorch::pytorch=1.9.0
  - python=3.9.5
  - r-cowplot=1.1.1
  - r-irkernel=1.2
  - r-tidyverse=1.3.1
  - scipy=1.6.3
  - scikit-learn=0.24.2
  - seaborn=0.11.1
  - tqdm=4.61.1
